### ISSUE TITLE
最低级的父级瓦片覆盖当前级别瓦片，绘制模糊

### ISSUE THREAD

**Issue by fuzhenn** [sakitam-gis/simple-terrain-viz#1]
maptalks的示例中，因为会同时加载3个级别的瓦片，最低级别瓦片因为覆盖的范围较大，会覆盖掉当前瓦片，出现模糊现象：

![image](https://user-images.githubusercontent.com/13678919/104399409-91364480-558b-11eb-8244-b36357078e0f.png)

解决方案是通过给不同级别瓦片，设置不同的stencil值，通过模板测试，来解决父级瓦片覆盖问题。
强制父级瓦片绘制时，子级别瓦片绘制的区域无法通过模板测试，就不会绘制了。

### 实现步骤:
* 把每个tile的zoom设置为mesh的stencil值
* stencil的func设为 <=

代码如下：
```js
stencil: {
    enable: true,
    func: {
      cmp: '<=',
      ref: (context, props) => { return props.zoom; }
    }
  },
```

### 参考资料
* [regl的stencil配置](https://github.com/regl-project/regl/blob/master/API.md#stencil)

**Comment by sakitam-fdd** [comment]
@fuzhenn 谢镇神，我再优化下:smile

**Comment by fuzhenn** [comment]
决定改写瓦片的加载方式，改写后瓦片不再会产生重叠。

**Comment by sakitam-fdd** [comment]
> 决定改写瓦片的加载方式，改写后瓦片不再会产生重叠。

棒👍
